# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-05 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newswebsite',
            name='allowed_domain',
            field=models.URLField(blank=True),
        ),
    ]
