# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-18 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_news', '0004_newswebsite_phantomjs_wait'),
    ]

    operations = [
        migrations.AddField(
            model_name='newswebsite',
            name='uuid_site_marchand',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='newswebsite',
            name='allowed_domain',
            field=models.CharField(blank=True, help_text='A domaine name without http:// or https://', max_length=200),
        ),
        migrations.AlterField(
            model_name='newswebsite',
            name='phantomjs_wait',
            field=models.IntegerField(default=0, help_text='Timout in seconds to wait by PhantomJs. Used only if PhantomJs is actived on the scraper'),
        ),
    ]
