# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-18 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_news', '0005_auto_20161118_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newswebsite',
            name='uuid_site_marchand',
            field=models.CharField(max_length=255),
        ),
    ]
