# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-02 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_scraper', '0017_added_order_to_scraped_obj_attr'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='pagination_xpath',
            field=models.CharField(default='', help_text='This xpath should returns a list of href values to follow', max_length=255),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='pagination_type',
            field=models.CharField(choices=[('N', 'NONE'), ('R', 'RANGE_FUNCT'), ('F', 'FREE_LIST'), ('X', 'XPATH')], default='N', max_length=1),
        ),
    ]
