# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-05 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_scraper', '0018_auto_20161102_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='stop_on_pagination_first_level',
            field=models.BooleanField(default=True),
        ),
    ]
