# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-05 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_scraper', '0019_scraper_stop_on_pagination_first_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='use_phantomjs',
            field=models.BooleanField(default=False),
        ),
    ]
