# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-18 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_scraper', '0020_scraper_use_phantomjs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='stop_on_pagination_first_level',
            field=models.BooleanField(default=True, help_text='If True the scraper will extract urls from first url and stop the pagination.'),
        ),
    ]
